// Generated by Selenium IDE
using AutoTest2.Data;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System.Collections.Generic;
using System.Threading;


namespace AutoTest2
{
    [TestFixture]
    public class Test2:TestBase
    {
        UserData userData = new UserData("Admin@admin.admin","a1s2d3f4");
        MessageData messageData = new MessageData("Hello from SendMessageTest!");

        [Test]
        public void GoToAdminPageTest()
        {
            GoToHomePage();
            GoToRegPage();
            ChangeRegPageToLogPage();
            Login(userData);
            GoToAdminPage();
        }

        [Test]
        public void SendMessageTest()
        {
            GoToHomePage();
            GoToRegPage();
            ChangeRegPageToLogPage();
            Login(userData);
            GoToBlogPage();
            GoToBlogPostPage();
            SendMessage(messageData);
        }
    }
}

